package kz.serik.factory;

public class ServiceConst {
    public static final String ADD_FILM = "/restricted/addfilm";
    public static final String ADD_FILM_JSP = "/restricted/addfilm.jsp";
    public static final String ERROR_SERVICE = "/error";
    public static final String ERROR_JSP = "/error.jsp";
    public static final String PASSWORD_UPDATE = "/secured/password_update";
    public static final String LOGIN = "/secured/login";
    public static final String LOGIN_JSP = "/login.jsp";
    public static final String LOGOUT = "/logout";
    public static final String PROFILE = "/secured/profile";
    public static final String PROFILE_JSP = "/secured/profile.jsp";
    public static final String INDEX = "/index";
    public static final String ROOT = "/";
    public static final String REGISTER = "/register";
    public static final String REGISTER_JSP = "/register.jsp";
    public static final String SEARCH = "/search";
    public static final String SEARCH_JSP = "/search.jsp";
    public static final String DETAILS = "/details";
    public static final String LOAD_COMMENTS = "/load_comments";
    public static final String ADD_LIKE = "/secured/add_like";
    public static final String ADD_COMMENTS = "/secured/add_comments";
    public static final String DELETE_COMMENTS = "/secured/delete_comments";
    public static final String EDIT_COMMENTS = "/secured/edit_comments";
    public static final String EDIT_FILM = "/restricted/edit_film";
    public static final String DELETE_FILM = "/restricted/delete_film";
    public static final String DELETE_USER = "/restricted/delete_user";
    public static final char[] HEX_ARRAY = "0123456789ABCDEF".toCharArray();
    public static final String POST = "POST";
    public static final String GET = "GET";
    public static final String UTF8 = "UTF8";
    public static final String MD5 = "MD5";
    public static final String CURRENT_USER ="CURRENT_USER";
    public static final String USERS_JSP = "/restricted/users.jsp";
    public static final String DETAILS_JSP = "/details.jsp";
    public static final String INDEX_JSP = "/index.jsp";
    public static final String EDIT_FILM_JSP = "/restricted/editfilm.jsp";
    public static final String ADMINISTRATOR = "administrator";
    public static final String CLIENT = "client";
}
